"""add ai message intelligence fields

Revision ID: 79b384e5ac08
Revises: eb169b2bf7ac
Create Date: 2026-08-02 15:33:20.879201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b384e5ac08'
down_revision: Union[str, Sequence[str], None] = 'eb169b2bf7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ai_category', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('ai_priority', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('ai_intent', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('ai_action_required', sa.Boolean(), nullable=False, server_default=sa.false()))
op.add_column( 'messages', sa.Column( 'ai_processed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'ai_processed')
    op.drop_column('messages', 'ai_action_required')
    op.drop_column('messages', 'ai_intent')
    op.drop_column('messages', 'ai_priority')
    op.drop_column('messages', 'ai_category')
    # ### end Alembic commands ###
