"""add message id to ai actions

Revision ID: 94c11fd344d2
Revises: f78d02306f8c
Create Date: 2026-08-03 21:21:39.489048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c11fd344d2'
down_revision: Union[str, Sequence[str], None] = 'f78d02306f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_actions', sa.Column('message_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ai_actions_message_id'), 'ai_actions', ['message_id'], unique=False)
    op.create_foreign_key(None, 'ai_actions', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_actions', type_='foreignkey')
    op.drop_index(op.f('ix_ai_actions_message_id'), table_name='ai_actions')
    op.drop_column('ai_actions', 'message_id')
    # ### end Alembic commands ###
