"""add appointment contacts

Revision ID: aa74a2b6701c
Revises: f27a5f457969
Create Date: 2026-08-02 01:10:05.952056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa74a2b6701c'
down_revision: Union[str, Sequence[str], None] = 'f27a5f457969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_appointments_contact_id'), 'appointments', ['contact_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_contact_id'), table_name='appointments')
    op.drop_column('appointments', 'contact_id')
    # ### end Alembic commands ###
