"""add integration to conversations

Revision ID: eb169b2bf7ac
Revises: f51ffc25e019
Create Date: 2026-08-02 14:44:32.489899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb169b2bf7ac'
down_revision: Union[str, Sequence[str], None] = 'f51ffc25e019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('integration_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_integration_id'), 'conversations', ['integration_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'integrations', ['integration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_integration_id'), table_name='conversations')
    op.drop_column('conversations', 'integration_id')
    # ### end Alembic commands ###
