"""enhance unified messaging models

Revision ID: f51ffc25e019
Revises: aa74a2b6701c
Create Date: 2026-08-02 10:57:51.161700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f51ffc25e019'
down_revision: Union[str, Sequence[str], None] = 'aa74a2b6701c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'company')
    op.add_column('conversations', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_conversations_integration_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_external_id'), 'conversations', ['external_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_platform'), 'conversations', ['platform'], unique=False)
    op.drop_constraint(op.f('conversations_integration_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'external_conversation_id')
    op.drop_column('conversations', 'integration_id')
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('platform', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('direction', sa.String(length=20), nullable=False))
    op.add_column('messages', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('sender_identifier', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('recipient_identifier', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('received_at', sa.DateTime(), nullable=False))
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_platform'), 'messages', ['platform'], unique=False)
    op.create_index(op.f('ix_messages_received_at'), 'messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'external_message_id')
    op.drop_column('messages', 'priority')
    op.drop_column('messages', 'requires_response')
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'ai_category')
    op.drop_column('messages', 'receiver')
    op.drop_column('messages', 'sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('receiver', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('ai_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('requires_response', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('external_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_received_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_platform'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.alter_column('messages', 'message_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('messages', 'received_at')
    op.drop_column('messages', 'recipient_identifier')
    op.drop_column('messages', 'sender_identifier')
    op.drop_column('messages', 'sender_name')
    op.drop_column('messages', 'direction')
    op.drop_column('messages', 'external_id')
    op.drop_column('messages', 'platform')
    op.drop_column('messages', 'user_id')
    op.add_column('conversations', sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('external_conversation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('conversations_integration_id_fkey'), 'conversations', 'integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_platform'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_external_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_integration_id'), 'conversations', ['integration_id'], unique=False)
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'external_id')
    op.add_column('contacts', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
