"""add ai processing status

Revision ID: f78d02306f8c
Revises: 79b384e5ac08
Create Date: 2026-08-02 23:03:11.555976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78d02306f8c'
down_revision: Union[str, Sequence[str], None] = '79b384e5ac08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "messages",
    sa.Column(
        "ai_status",
        sa.String(length=20),
        nullable=False,
        server_default="pending",
    ),
)
    op.create_index(op.f('ix_messages_ai_status'), 'messages', ['ai_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_ai_status'), table_name='messages')
    op.drop_column('messages', 'ai_status')
    # ### end Alembic commands ###
